#!/bin/sh

if [ "$1" = "--config" ]
then
  shift
  if [ "$1" = "syntax" ]
  then
    echo name
    exit 0
  fi
  echo "$0: Unknown option '--config $1'" >&2
  exit 1
fi

case "$1" in
    name)
	hostname
	;;

    *)
	echo "Syntax error" >&1
	exit 1
	;;
esac
